Script started on Mon 09 Mar 2015 09:31:05 PM MDT
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ gcc difference.c
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ ./s.out
bash: ./s.out: No such file or directory
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ ./s.[K[Ka.out
sum of squares: 338350
square of sum: 25502500
difference: 25164150
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ exit
exit

Script done on Mon 09 Mar 2015 09:31:22 PM MDT
