Script started on Mon 09 Mar 2015 09:29:07 PM MDT
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ gcc -c zombie.c
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ gcc lab5.c zombie.o
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ ./a.out
1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
1

Was the zombie found dead? Y or N
>>Y

Please enter the number of toes the zombie had
>> 1
Please choose the day this zombie was encountered:
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 1

Enter the time when this zombie was encountered.
Seperate hours, minutes, and seconds by  colons
HH:MM:SS
>> q 1:1:1
1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
1

Was the zombie found dead? Y or N
>>Y

Please enter the number of toes the zombie had
>> 2
Please choose the day this zombie was encountered:
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 2

Enter the time when this zombie was encountered.
Seperate hours, minutes, and seconds by  colons
HH:MM:SS
>> 2:2:2
1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
1

Was the zombie found dead? Y or N
>>n

Please enter the amount of blood that oozed from its body after you killed it(in mL)
>> 3
Please choose the day this zombie was encountered:
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 3

Enter the time when this zombie was encountered.
Seperate hours, minutes, and seconds by  colons
HH:MM:SS
>> 3:3:3
1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
1

Was the zombie found dead? Y or N
>>4
Please choose the day this zombie was encountered:
1) Monday
2) Tuesday
3) Wednesday
4) Thursday
5) Friday
6) Saturday
7) Sunday
>> 4

Enter the time when this zombie was encountered.
Seperate hours, minutes, and seconds by  colons
HH:MM:SS
>> 4:4:4
1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
2

1.) This zombie was found dead.
It had 1 toes.
This zombie was sighted on Sunday at 01:01:01


2.) This zombie was found dead.
It had 2 toes.
This zombie was sighted on Monday at 02:02:02


3.) This zombie was found ALIVE!
It was drained of 3.000000mL of blood once killed.
>>This zombie was sighted on Tuesday at 03:03:03

1) Enter new zombie information
2) Display zombie information
3) Return to fighting zombies (exit)
3
Stay alert! Keep a watch out for zombies!

GOODBYE and GOOD LUCK!
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab5noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab5$ exit
exit

Script done on Mon 09 Mar 2015 09:30:38 PM MDT
