Script started on Fri 10 Apr 2015 10:30:50 AM MDT
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab9noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab9$ gcc -wall [K[K[K[K[KWall lab9.c
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab9noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab9$ valgrind --leak-check =full ./a.out
==6806== Memcheck, a memory error detector
==6806== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==6806== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==6806== Command: ./a.out
==6806== 
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
1

what value will this node hold?
1
where will it go?
1) Head
2) Tail
3) Middle
1
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
1

what value will this node hold?
2
where will it go?
1) Head
2) Tail
3) Middle
1
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
1

what value will this node hold?
3
where will it go?
1) Head
2) Tail
3) Middle
1
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
3
node 1:address 0xbef2dcd0, data 3.000000, next 0x41fc068
node 2:address 0xbef2dcd0, data 2.000000, next 0x41fc028
node 3:address 0xbef2dcd0, data 1.000000, next (nil)
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
1

what value will this node hold?
2
where will it go?
1) Head
2) Tail
3) Middle
2
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
1

what value will this node hold?
3
where will it go?
1) Head
2) Tail
3) Middle
2
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
3
node 1:address 0xbef2dcd0, data 3.000000, next 0x41fc068
node 2:address 0xbef2dcd0, data 2.000000, next 0x41fc028
node 3:address 0xbef2dcd0, data 1.000000, next 0x41fc0e8
node 4:address 0xbef2dcd0, data 2.000000, next 0x41fc128
node 5:address 0xbef2dcd0, data 3.000000, next (nil)
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
1

what value will this node hold?
4
where will it go?
1) Head
2) Tail
3) Middle
3
where will it go?
2
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
1

what value will this node hold?
4
where will it go?
1) Head
2) Tail
3) Middle
3
where will it go?
5
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
3
node 1:address 0xbef2dcd0, data 3.000000, next 0x41fc168
node 2:address 0xbef2dcd0, data 4.000000, next 0x41fc068
node 3:address 0xbef2dcd0, data 2.000000, next 0x41fc028
node 4:address 0xbef2dcd0, data 1.000000, next 0x41fc1a8
node 5:address 0xbef2dcd0, data 4.000000, next 0x41fc0e8
node 6:address 0xbef2dcd0, data 2.000000, next 0x41fc128
node 7:address 0xbef2dcd0, data 3.000000, next (nil)
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
4
you have 7 linked nodes
0xbef2dce4
1) Enter a number
2) Delete a number
3) Print all numbers
4) Display node count
5) End program
5

EXITING
==6806== 
==6806== HEAP SUMMARY:
==6806==     in use at exit: 0 bytes in 0 blocks
==6806==   total heap usage: 7 allocs, 7 frees, 84 bytes allocated
==6806== 
==6806== All heap blocks were freed -- no leaks are possible
==6806== 
==6806== For counts of detected and suppressed errors, rerun with: -v
==6806== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab9noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab9$ exit
exit

Script done on Fri 10 Apr 2015 10:32:26 AM MDT
