Script started on Mon 02 Mar 2015 09:12:24 PM MST
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ gcc array
gcc: error: array: No such file or directory
gcc: fatal error: no input files
compilation terminated.
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ gcc array_script.c
gcc: error: array_script.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ ./a.[K[K[K[Kgcc array_script.c[C[1P.c[1P.c[1P.c[1P.c[1P.ct.cr.cu.cc.ct.c
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ ./a.out
min age subject:
	subject: C
	age: 19
	height: 68
max age aubject:
	subject: A
	age: 23
	height: 74
min height subject:
	subject: E
	age: 22
	height: 62
max height subject:
	subject: D
	age: 20
	height: 76
average age of subjects: 21.199997
average height of subjects: 68.800000
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ exit
exit

Script done on Mon 02 Mar 2015 09:13:04 PM MST
