Script started on Mon 02 Mar 2015 09:09:59 PM MST
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ gcc lab4_q5.c
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ ./a.out
Enter the integer corresponding to the color
1.) Red
2.) Orange
3.) Yellow
4.) Green
5.) Blue
6.) Indigo
7.) Violet
or 20 to quit
2
Orange
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ ./a.out
Enter the integer corresponding to the color
1.) Red
2.) Orange
3.) Yellow
4.) Green
5.) Blue
6.) Indigo
7.) Violet
or 20 to quit
1
Red
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ ./a.out
Enter the integer corresponding to the color
1.) Red
2.) Orange
3.) Yellow
4.) Green
5.) Blue
6.) Indigo
7.) Violet
or 20 to quit
3
Yellow
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ ./a.out
Enter the integer corresponding to the color
1.) Red
2.) Orange
3.) Yellow
4.) Green
5.) Blue
6.) Indigo
7.) Violet
or 20 to quit
4
Green
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ ./a.out
Enter the integer corresponding to the color
1.) Red
2.) Orange
3.) Yellow
4.) Green
5.) Blue
6.) Indigo
7.) Violet
or 20 to quit
5
Blue
]0;noah@noah-HP-Mini-110-1000: ~/Documents/CSE113/sp2015/lab4noah@noah-HP-Mini-110-1000:~/Documents/CSE113/sp2015/lab4$ exit
exit

Script done on Mon 02 Mar 2015 09:10:37 PM MST
